"""public v2 schema

Revision ID: a509623c6959
Revises:
Create Date: 2026-07-31 11:32:24.696619
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a509623c6959'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_rate_limit_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_key', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_rate_limit_buckets')),
    sa.UniqueConstraint('subject_key', 'scope', 'window_start', name='uq_rate_limit_subject_scope_window')
    )
    with op.batch_alter_table('api_rate_limit_buckets', schema=None) as batch_op:
        batch_op.create_index('ix_rate_limit_buckets_subject_key_scope_window_start', ['subject_key', 'scope', 'window_start'], unique=False)

    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_active', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('streak', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_entries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('preferences', sa.JSON(), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_users'))
    )
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('telegram_update_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('update_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='processing', nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_category', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_update_receipts')),
    sa.UniqueConstraint('update_id', name=op.f('uq_telegram_update_receipts_update_id'))
    )
    op.create_table('account_export_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('requested_at_utc', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('object_key', sa.String(length=512), nullable=True),
    sa.Column('last_error_category', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], name=op.f('fk_account_export_requests_owner_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_account_export_requests'))
    )
    with op.batch_alter_table('account_export_requests', schema=None) as batch_op:
        batch_op.create_index('ix_account_export_requests_owner_id_requested_at_utc', ['owner_id', 'requested_at_utc'], unique=False)

    op.create_table('digest_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('digest_week_start', sa.Date(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('delivered_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_category', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], name=op.f('fk_digest_deliveries_owner_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_digest_deliveries')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_digest_deliveries_idempotency_key')),
    sa.UniqueConstraint('owner_id', 'digest_week_start', name='uq_digest_deliveries_owner_week')
    )
    with op.batch_alter_table('digest_deliveries', schema=None) as batch_op:
        batch_op.create_index('ix_digest_deliveries_owner_id_digest_week_start', ['owner_id', 'digest_week_start'], unique=False)

    op.create_table('invite_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('created_by_owner_id', sa.Integer(), nullable=True),
    sa.Column('claimed_by_owner_id', sa.Integer(), nullable=True),
    sa.Column('expires_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claimed_by_owner_id'], ['app_users.id'], name=op.f('fk_invite_codes_claimed_by_owner_id_app_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_owner_id'], ['app_users.id'], name=op.f('fk_invite_codes_created_by_owner_id_app_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invite_codes')),
    sa.UniqueConstraint('code_hash', name=op.f('uq_invite_codes_code_hash'))
    )
    op.create_table('ledger_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('transaction_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_local_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('capture_source', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("direction IN ('expense', 'income')", name=op.f('ck_ledger_entries_direction_supported')),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_ledger_entries_amount_positive')),
    sa.CheckConstraint('currency = UPPER(currency) AND length(currency) = 3', name=op.f('ck_ledger_entries_currency_iso_format')),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], name=op.f('fk_ledger_entries_owner_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries')),
    sa.UniqueConstraint('owner_id', 'idempotency_key', name='uq_ledger_entries_owner_id_idempotency_key')
    )
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.create_index('ix_ledger_entries_owner_id_category', ['owner_id', 'category'], unique=False)
        batch_op.create_index('ix_ledger_entries_owner_id_transaction_at_utc', ['owner_id', 'transaction_at_utc'], unique=False)
        batch_op.create_index('ix_ledger_entries_owner_id_user_local_date_currency', ['owner_id', 'user_local_date', 'currency'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('pinned', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('capture_source', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], name=op.f('fk_notes_owner_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes')),
    sa.UniqueConstraint('owner_id', 'idempotency_key', name='uq_notes_owner_id_idempotency_key')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index('ix_notes_owner_id_pinned', ['owner_id', 'pinned'], unique=False)
        batch_op.create_index('ix_notes_owner_id_updated_at', ['owner_id', 'updated_at'], unique=False)

    op.create_table('nutrition_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('meal_name', sa.String(length=128), nullable=True),
    sa.Column('logged_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_local_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('total_calories', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total_protein_grams', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('total_carbohydrate_grams', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('total_fat_grams', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('estimation_source', sa.String(length=64), nullable=False),
    sa.Column('overall_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confirmed_by_user', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('user_modified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('overall_confidence IS NULL OR (overall_confidence >= 0 AND overall_confidence <= 1)', name=op.f('ck_nutrition_logs_confidence_range')),
    sa.CheckConstraint('total_calories >= 0', name=op.f('ck_nutrition_logs_calories_nonnegative')),
    sa.CheckConstraint('total_carbohydrate_grams IS NULL OR total_carbohydrate_grams >= 0', name=op.f('ck_nutrition_logs_carbohydrate_nonnegative')),
    sa.CheckConstraint('total_fat_grams IS NULL OR total_fat_grams >= 0', name=op.f('ck_nutrition_logs_fat_nonnegative')),
    sa.CheckConstraint('total_protein_grams >= 0', name=op.f('ck_nutrition_logs_protein_nonnegative')),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], name=op.f('fk_nutrition_logs_owner_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_logs')),
    sa.UniqueConstraint('owner_id', 'idempotency_key', name='uq_nutrition_logs_owner_id_idempotency_key')
    )
    with op.batch_alter_table('nutrition_logs', schema=None) as batch_op:
        batch_op.create_index('ix_nutrition_logs_owner_id_logged_at_utc', ['owner_id', 'logged_at_utc'], unique=False)
        batch_op.create_index('ix_nutrition_logs_owner_id_user_local_date', ['owner_id', 'user_local_date'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('schedule_type', sa.String(length=16), nullable=False),
    sa.Column('scheduled_local_time', sa.String(length=8), nullable=True),
    sa.Column('next_run_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurrence_rule', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_run_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error_category', sa.String(length=64), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("schedule_type IN ('once', 'daily', 'weekly')", name=op.f('ck_reminders_schedule_type_supported')),
    sa.CheckConstraint('retry_count >= 0', name=op.f('ck_reminders_retry_count_nonnegative')),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], name=op.f('fk_reminders_owner_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminders')),
    sa.UniqueConstraint('owner_id', 'idempotency_key', name='uq_reminders_owner_id_idempotency_key')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index('ix_reminders_owner_id_enabled_next_run_at_utc', ['owner_id', 'enabled', 'next_run_at_utc'], unique=False)

    op.create_table('scheduled_digests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('weekday', sa.Integer(), server_default='6', nullable=False),
    sa.Column('scheduled_local_time', sa.String(length=8), nullable=False),
    sa.Column('next_run_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('weekday >= 0 AND weekday <= 6', name=op.f('ck_scheduled_digests_weekday_range')),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], name=op.f('fk_scheduled_digests_owner_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_digests')),
    sa.UniqueConstraint('owner_id', name='uq_scheduled_digests_owner_id')
    )
    with op.batch_alter_table('scheduled_digests', schema=None) as batch_op:
        batch_op.create_index('ix_scheduled_digests_owner_id_enabled_next_run_at_utc', ['owner_id', 'enabled', 'next_run_at_utc'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], name=op.f('fk_sessions_owner_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash'))
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index('ix_sessions_owner_id_expires_at_utc', ['owner_id', 'expires_at_utc'], unique=False)

    op.create_table('telegram_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('telegram_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('processed_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delete_after_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("direction IN ('inbound', 'outbound')", name=op.f('ck_telegram_messages_direction_supported')),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], name=op.f('fk_telegram_messages_owner_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_messages')),
    sa.UniqueConstraint('telegram_chat_id', 'telegram_message_id', name='uq_telegram_messages_chat_message')
    )
    with op.batch_alter_table('telegram_messages', schema=None) as batch_op:
        batch_op.create_index('ix_telegram_messages_owner_id_delete_after_utc', ['owner_id', 'delete_after_utc'], unique=False)

    op.create_table('tracked_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('current_value', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'paused', 'completed')", name=op.f('ck_tracked_goals_status_supported')),
    sa.CheckConstraint('current_value >= 0', name=op.f('ck_tracked_goals_current_nonnegative')),
    sa.CheckConstraint('due_date IS NULL OR due_date >= start_date', name=op.f('ck_tracked_goals_due_date_after_start')),
    sa.CheckConstraint('target_value IS NULL OR target_value >= 0', name=op.f('ck_tracked_goals_target_nonnegative')),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], name=op.f('fk_tracked_goals_owner_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tracked_goals')),
    sa.UniqueConstraint('owner_id', 'idempotency_key', name='uq_tracked_goals_owner_id_idempotency_key')
    )
    with op.batch_alter_table('tracked_goals', schema=None) as batch_op:
        batch_op.create_index('ix_tracked_goals_owner_id_due_date', ['owner_id', 'due_date'], unique=False)
        batch_op.create_index('ix_tracked_goals_owner_id_status', ['owner_id', 'status'], unique=False)

    op.create_table('user_preferences',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=True),
    sa.Column('sunday_digest_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('calorie_target', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('protein_target_grams', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('carbohydrate_target_grams', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('fat_target_grams', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('calorie_target IS NULL OR calorie_target >= 0', name=op.f('ck_user_preferences_calorie_target_nonnegative')),
    sa.CheckConstraint('carbohydrate_target_grams IS NULL OR carbohydrate_target_grams >= 0', name=op.f('ck_user_preferences_carbohydrate_target_nonnegative')),
    sa.CheckConstraint('fat_target_grams IS NULL OR fat_target_grams >= 0', name=op.f('ck_user_preferences_fat_target_nonnegative')),
    sa.CheckConstraint('protein_target_grams IS NULL OR protein_target_grams >= 0', name=op.f('ck_user_preferences_protein_target_nonnegative')),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], name=op.f('fk_user_preferences_owner_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('owner_id', name=op.f('pk_user_preferences'))
    )
    op.create_table('work_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('tags', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('logged_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_local_date', sa.Date(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('capture_source', sa.String(length=32), nullable=False),
    sa.Column('voice_file_id', sa.String(length=255), nullable=True),
    sa.Column('legacy_raw_entry_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], name=op.f('fk_work_logs_owner_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_logs')),
    sa.UniqueConstraint('legacy_raw_entry_id', name=op.f('uq_work_logs_legacy_raw_entry_id')),
    sa.UniqueConstraint('owner_id', 'idempotency_key', name='uq_work_logs_owner_id_idempotency_key')
    )
    with op.batch_alter_table('work_logs', schema=None) as batch_op:
        batch_op.create_index('ix_work_logs_owner_id_category', ['owner_id', 'category'], unique=False)
        batch_op.create_index('ix_work_logs_owner_id_logged_at_utc', ['owner_id', 'logged_at_utc'], unique=False)
        batch_op.create_index('ix_work_logs_owner_id_user_local_date', ['owner_id', 'user_local_date'], unique=False)

    op.create_table('nutrition_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nutrition_log_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('original_item_text', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('quantity_value', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('quantity_unit', sa.String(length=32), nullable=True),
    sa.Column('portion_description', sa.String(length=255), nullable=True),
    sa.Column('estimated_grams', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('calories', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('protein_grams', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('carbohydrate_grams', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('fat_grams', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('estimation_source', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('user_modified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('calories >= 0', name=op.f('ck_nutrition_items_calories_nonnegative')),
    sa.CheckConstraint('carbohydrate_grams IS NULL OR carbohydrate_grams >= 0', name=op.f('ck_nutrition_items_carbohydrate_nonnegative')),
    sa.CheckConstraint('confidence IS NULL OR (confidence >= 0 AND confidence <= 1)', name=op.f('ck_nutrition_items_confidence_range')),
    sa.CheckConstraint('estimated_grams IS NULL OR estimated_grams >= 0', name=op.f('ck_nutrition_items_estimated_grams_nonnegative')),
    sa.CheckConstraint('fat_grams IS NULL OR fat_grams >= 0', name=op.f('ck_nutrition_items_fat_nonnegative')),
    sa.CheckConstraint('protein_grams >= 0', name=op.f('ck_nutrition_items_protein_nonnegative')),
    sa.CheckConstraint('quantity_value IS NULL OR quantity_value > 0', name=op.f('ck_nutrition_items_quantity_positive')),
    sa.ForeignKeyConstraint(['nutrition_log_id'], ['nutrition_logs.id'], name=op.f('fk_nutrition_items_nutrition_log_id_nutrition_logs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], name=op.f('fk_nutrition_items_owner_id_app_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nutrition_items'))
    )
    with op.batch_alter_table('nutrition_items', schema=None) as batch_op:
        batch_op.create_index('ix_nutrition_items_owner_id_nutrition_log_id', ['owner_id', 'nutrition_log_id'], unique=False)

    op.create_table('reminder_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_occurrence_at_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('delivered_at_utc', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_category', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'claimed', 'sent', 'failed', 'cancelled')", name=op.f('ck_reminder_deliveries_status_supported')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_reminder_deliveries_attempt_count_nonnegative')),
    sa.ForeignKeyConstraint(['owner_id'], ['app_users.id'], name=op.f('fk_reminder_deliveries_owner_id_app_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], name=op.f('fk_reminder_deliveries_reminder_id_reminders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reminder_deliveries')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_reminder_deliveries_idempotency_key')),
    sa.UniqueConstraint('reminder_id', 'scheduled_occurrence_at_utc', name='uq_reminder_delivery_occurrence')
    )
    with op.batch_alter_table('reminder_deliveries', schema=None) as batch_op:
        batch_op.create_index('ix_reminder_deliveries_owner_id_status', ['owner_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder_deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_reminder_deliveries_owner_id_status')

    op.drop_table('reminder_deliveries')
    with op.batch_alter_table('nutrition_items', schema=None) as batch_op:
        batch_op.drop_index('ix_nutrition_items_owner_id_nutrition_log_id')

    op.drop_table('nutrition_items')
    with op.batch_alter_table('work_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_work_logs_owner_id_user_local_date')
        batch_op.drop_index('ix_work_logs_owner_id_logged_at_utc')
        batch_op.drop_index('ix_work_logs_owner_id_category')

    op.drop_table('work_logs')
    op.drop_table('user_preferences')
    with op.batch_alter_table('tracked_goals', schema=None) as batch_op:
        batch_op.drop_index('ix_tracked_goals_owner_id_status')
        batch_op.drop_index('ix_tracked_goals_owner_id_due_date')

    op.drop_table('tracked_goals')
    with op.batch_alter_table('telegram_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_telegram_messages_owner_id_delete_after_utc')

    op.drop_table('telegram_messages')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_sessions_owner_id_expires_at_utc')

    op.drop_table('sessions')
    with op.batch_alter_table('scheduled_digests', schema=None) as batch_op:
        batch_op.drop_index('ix_scheduled_digests_owner_id_enabled_next_run_at_utc')

    op.drop_table('scheduled_digests')
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index('ix_reminders_owner_id_enabled_next_run_at_utc')

    op.drop_table('reminders')
    with op.batch_alter_table('nutrition_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_nutrition_logs_owner_id_user_local_date')
        batch_op.drop_index('ix_nutrition_logs_owner_id_logged_at_utc')

    op.drop_table('nutrition_logs')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index('ix_notes_owner_id_updated_at')
        batch_op.drop_index('ix_notes_owner_id_pinned')

    op.drop_table('notes')
    with op.batch_alter_table('ledger_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_ledger_entries_owner_id_user_local_date_currency')
        batch_op.drop_index('ix_ledger_entries_owner_id_transaction_at_utc')
        batch_op.drop_index('ix_ledger_entries_owner_id_category')

    op.drop_table('ledger_entries')
    op.drop_table('invite_codes')
    with op.batch_alter_table('digest_deliveries', schema=None) as batch_op:
        batch_op.drop_index('ix_digest_deliveries_owner_id_digest_week_start')

    op.drop_table('digest_deliveries')
    with op.batch_alter_table('account_export_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_account_export_requests_owner_id_requested_at_utc')

    op.drop_table('account_export_requests')
    op.drop_table('telegram_update_receipts')
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_users_telegram_id'))

    op.drop_table('app_users')
    with op.batch_alter_table('api_rate_limit_buckets', schema=None) as batch_op:
        batch_op.drop_index('ix_rate_limit_buckets_subject_key_scope_window_start')

    op.drop_table('api_rate_limit_buckets')
    # ### end Alembic commands ###
